version: '3'

services:
  # scraper for aliexpress
  scrapy-aliexpress: 
    build: .
    image: python-scrapy-image
    hostname: scrapy-aliexpress
    container_name: scrapy-aliexpress
    ports:
      # mongodb port
      - 27024:27017
    links:
      - scrapy-secondary-aliexpress-1
      - scrapy-secondary-aliexpress-2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - python-aliexpress
    tty: true


  # replicat 1
  scrapy-secondary-aliexpress-1: 
    image: mongo
    hostname: scrapy-secondary-aliexpress-1
    container_name: scrapy-secondary-aliexpress-1
    
    ports:
      # mongodb port
      - 27025:27017
    networks:
      - python-aliexpress
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    tty: true

# replicat 2
  scrapy-secondary-aliexpress-2: 
    image: mongo
    hostname: scrapy-secondary-aliexpress-2
    container_name: scrapy-secondary-aliexpress-2
    
    ports:
      # mongodb port
      - 27026:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - python-aliexpress
    tty: true


networks:
  python-aliexpress: {}
