FROM ubuntu:latest

LABEL maintainer = "@Red_One"
WORKDIR /root

RUN apt-get update && \
    apt-get install -y \
    openssh-server \
    openjdk-8-jdk \
    wget \
    nano

RUN wget https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz && \
    tar -xzvf kafka_2.13-3.1.0.tgz && \
    mv kafka_2.13-3.1.0 /usr/local/kafka && \
    rm kafka_2.13-3.1.0.tgz

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV KAFKA_HOME=/usr/local/kafka

COPY config/* /tmp/ 

RUN mv /tmp/start_kafka.sh ~/ && \
    mv /tmp/server.properties  $KAFKA_HOME/config/server.properties

RUN chmod +x ~/start_kafka.sh


CMD [ "sh", "-c", "/root/start_kafka.sh"]